import type { Question } from "./types";

export const FEDERAL_QUESTIONS: Question[] = [
  {
    id: "fed-001",
    domain: "federal_requirements",
    stem: "Under the Combat Methamphetamine Epidemic Act, which statement about pseudoephedrine sales is most accurate at a high level?",
    choices: ["Daily and 30-day purchase limits apply, with logbook and ID requirements in regulated sellers", "There are no federal quantity limits if the product is behind the counter", "Pseudoephedrine may be sold freely like regular OTC candy", "Only Schedule II prescriptions can include pseudoephedrine"],
    correctIndex: 0,
    rationale: "CMEA sets purchase limits and requires ID/logbook processes for regulated sellers.",
    topicTags: ["pseudoephedrine", "CMEA"],
  },
  {
    id: "fed-002",
    domain: "federal_requirements",
    stem: "HIPAA's minimum necessary standard generally means:",
    choices: ["Use or disclose only the PHI needed for the intended purpose", "Share full charts with any caller who knows the patient name", "Post PHI on social media if de-identified by first name only", "Technicians may never view any PHI"],
    correctIndex: 0,
    rationale: "Minimum necessary limits PHI use/disclosure to what is needed.",
    topicTags: ["HIPAA", "privacy"],
  },
  {
    id: "fed-003",
    domain: "federal_requirements",
    stem: "DSCSA primarily addresses:",
    choices: ["Pharmaceutical supply chain security and tracing of certain prescription products", "Medicare Part D premium calculations", "Technician national certification fees", "USP compounding chapter numbering only"],
    correctIndex: 0,
    rationale: "The Drug Supply Chain Security Act focuses on tracing and suspect product handling.",
    topicTags: ["DSCSA", "supply-chain"],
  },
  {
    id: "fed-004",
    domain: "federal_requirements",
    stem: "A Class I FDA recall typically involves:",
    choices: ["A situation where use/exposure may cause serious adverse health consequences or death", "Only labeling typos with no health risk", "Voluntary market withdrawals for marketing reasons only", "Recalls limited to veterinary feed"],
    correctIndex: 0,
    rationale: "Class I recalls involve reasonable probability of serious harm or death.",
    topicTags: ["recalls", "FDA"],
  },
  {
    id: "fed-005",
    domain: "federal_requirements",
    stem: "Which DEA form is historically associated with ordering Schedule I/II controlled substances?",
    choices: ["DEA Form 222", "DEA Form 41 only for all retail sales", "CMS-1500", "FDA Form 3500A only"],
    correctIndex: 0,
    rationale: "DEA Form 222 (and electronic CSOS) is used for CI/CII ordering.",
    topicTags: ["DEA", "controlled-substances"],
  },
  {
    id: "fed-006",
    domain: "federal_requirements",
    stem: "Protected Health Information (PHI) under HIPAA includes:",
    choices: ["Individually identifiable health information held by covered entities/business associates", "Only paper prescriptions older than 10 years", "Drug prices on a public website with no patient data", "DEA registrant numbers of pharmacies alone"],
    correctIndex: 0,
    rationale: "PHI is individually identifiable health information in covered contexts.",
    topicTags: ["HIPAA"],
  },
  {
    id: "fed-007",
    domain: "federal_requirements",
    stem: "A Class III recall generally indicates:",
    choices: ["Use/exposure is not likely to cause adverse health consequences", "Immediate life-threatening risk in all cases", "Automatic criminal liability for technicians", "That the product is Schedule I"],
    correctIndex: 0,
    rationale: "Class III: not likely to cause adverse health consequences.",
    topicTags: ["recalls"],
  },
  {
    id: "fed-008",
    domain: "federal_requirements",
    stem: "Under DSCSA concepts, a suspect product is one that:",
    choices: ["A trading partner has reason to believe may be counterfeit, diverted, stolen, or otherwise unfit", "Has a higher copay than expected", "Was dispensed with a counseling offer declined", "Is within 90 days of beyond-use date only"],
    correctIndex: 0,
    rationale: "Suspect product determinations relate to potential illegitimate supply-chain issues.",
    topicTags: ["DSCSA"],
  },
  {
    id: "fed-009",
    domain: "federal_requirements",
    stem: "Federal controlled substance schedules range from:",
    choices: ["Schedule I (highest abuse / no accepted medical use federally) through Schedule V", "Schedule A through Schedule E only", "OTC Tier 1 through 3", "USP Chapters 795 through 800"],
    correctIndex: 0,
    rationale: "CSA schedules are I through V.",
    topicTags: ["schedules", "CSA"],
  },
  {
    id: "fed-010",
    domain: "federal_requirements",
    stem: "Which practice best aligns with HIPAA privacy in a retail pharmacy?",
    choices: ["Verify identity appropriately before discussing therapy details and avoid public PHI disclosure", "Announce full medication lists over the intercom", "Email PHI to personal accounts without safeguards because it is faster", "Leave printed labels face-up at the register overnight"],
    correctIndex: 0,
    rationale: "Identity verification and safeguarding PHI are core privacy practices.",
    topicTags: ["HIPAA"],
  },
  {
    id: "fed-011",
    domain: "federal_requirements",
    stem: "Pseudoephedrine purchase limits under federal CMEA for retail sellers are commonly described as:",
    choices: ["3.6 g/day and 9 g/30 days (base) with nuances by package and seller type", "Unlimited if the buyer is over 18", "1 tablet per lifetime", "Only applicable to Schedule II prescriptions"],
    correctIndex: 0,
    rationale: "Federal retail limits are commonly taught as 3.6 g/day and 9 g per 30 days.",
    topicTags: ["pseudoephedrine", "CMEA"],
    needsReview: true,
  },
  {
    id: "fed-012",
    domain: "federal_requirements",
    stem: "A Class II recall typically means:",
    choices: ["Use/exposure may cause temporary or medically reversible adverse health consequences, or serious harm probability is remote", "Certain death in all exposed patients", "No FDA involvement ever", "Automatic Schedule II reclassification"],
    correctIndex: 0,
    rationale: "Class II involves temporary/reversible consequences or remote probability of serious harm.",
    topicTags: ["recalls"],
  },
  {
    id: "fed-013",
    domain: "federal_requirements",
    stem: "Which statement about transferring prescriptions for controlled substances is most accurate at a federal awareness level?",
    choices: ["Federal rules differ by schedule; CII transfers are highly restricted compared with III-V in many contexts", "Any controlled prescription may be transferred unlimited times like noncontrols", "Technicians may independently authorize interstate CII transfers without a pharmacist", "HIPAA bans all transfers"],
    correctIndex: 0,
    rationale: "CII transfer rules are stricter; III-V have specific allowance frameworks. Exact current electronic exceptions are QC-sensitive.",
    topicTags: ["controlled-substances", "transfers"],
    needsReview: true,
  },
  {
    id: "fed-014",
    domain: "federal_requirements",
    stem: "Covered entities under HIPAA generally include:",
    choices: ["Health plans, health care clearinghouses, and health care providers who transmit certain electronic transactions", "Only software vendors", "Only cash-pay compounding pharmacies outside the US", "Patients themselves as covered entities"],
    correctIndex: 0,
    rationale: "The classic covered entity triad is plans, clearinghouses, and specified providers.",
    topicTags: ["HIPAA"],
  },
  {
    id: "fed-015",
    domain: "federal_requirements",
    stem: "Product identifiers used in DSCSA tracing commonly include:",
    choices: ["NDC, serial number, lot, and expiration in a standardized identifier package", "Only the patient's date of birth", "Only the pharmacy NPI", "Only the AWP"],
    correctIndex: 0,
    rationale: "DSCSA serialization uses NDC, serial, lot, and expiration elements.",
    topicTags: ["DSCSA", "NDC"],
  },
  {
    id: "fed-016",
    domain: "federal_requirements",
    stem: "Which action is inappropriate regarding PHI?",
    choices: ["Discussing a patient's HIV therapy loudly in a crowded waiting area", "Using a private counseling area when available", "Logging off shared terminals", "Using minimum necessary for insurance helpdesk calls"],
    correctIndex: 0,
    rationale: "Public discussion of sensitive PHI violates privacy expectations.",
    topicTags: ["HIPAA"],
  },
  {
    id: "fed-017",
    domain: "federal_requirements",
    stem: "Federal law places heroin in which schedule?",
    choices: ["Schedule I", "Schedule II", "Schedule III", "Schedule V"],
    correctIndex: 0,
    rationale: "Heroin is Schedule I federally.",
    topicTags: ["schedules"],
  },
  {
    id: "fed-018",
    domain: "federal_requirements",
    stem: "When a recall is issued, pharmacy staff should generally:",
    choices: ["Follow pharmacy policies to identify, quarantine, and process affected stock and notify appropriate parties per protocol", "Ignore Class II and III recalls", "Destroy all inventory of that manufacturer regardless of lot", "Post patient names online for transparency"],
    correctIndex: 0,
    rationale: "Recall response is lot/product-specific and policy-driven.",
    topicTags: ["recalls", "quality"],
  },
  {
    id: "fed-019",
    domain: "federal_requirements",
    stem: "Which best describes a business associate under HIPAA?",
    choices: ["A person/entity that performs functions involving PHI for a covered entity under a BAA", "Any customer who pays cash", "Any drug wholesaler employee off duty", "A patient's family member"],
    correctIndex: 0,
    rationale: "Business associates handle PHI on behalf of covered entities under agreements.",
    topicTags: ["HIPAA"],
  },
  {
    id: "fed-p01",
    domain: "federal_requirements",
    stem: "Which statement about OTC pseudoephedrine is true?",
    choices: ["It is kept behind the counter with ID/log requirements in regulated retail settings", "It is Schedule II requiring a written Rx always", "It has no purchase tracking", "It may be sold to minors without restriction federally"],
    correctIndex: 0,
    rationale: "CMEA places PSE behind the counter with ID/log rules.",
    topicTags: ["pseudoephedrine"],
    paidOnly: true,
  },
  {
    id: "fed-p02",
    domain: "federal_requirements",
    stem: "Illegitimate product under DSCSA concepts includes product that:",
    choices: ["Is counterfeit, diverted, or stolen, among other unfit categories", "Has a patient-preferred flavor", "Was dispensed with a coupon", "Has a high deductible plan"],
    correctIndex: 0,
    rationale: "Illegitimate products include counterfeit/diverted/stolen etc.",
    topicTags: ["DSCSA"],
    paidOnly: true,
  },
  {
    id: "fed-p03",
    domain: "federal_requirements",
    stem: "Which is an example of safeguarding PHI?",
    choices: ["Placing discarded labels in secure PHI destruction bins", "Throwing labeled vials in open dumpsters", "Texting full Rx images to friends for help", "Leaving monitors unlocked overnight"],
    correctIndex: 0,
    rationale: "Secure destruction protects PHI.",
    topicTags: ["HIPAA"],
    paidOnly: true,
  },
  {
    id: "fed-p04",
    domain: "federal_requirements",
    stem: "DEA registrant pharmacies must follow controlled substance inventory and recordkeeping rules that generally require:",
    choices: ["Accurate records of receipt and dispensing of controlled substances", "No records if the drug is paid cash", "Verbal-only logs without dates", "Storing CII with OTC candy"],
    correctIndex: 0,
    rationale: "CSA requires controlled substance records.",
    topicTags: ["DEA", "recordkeeping"],
    paidOnly: true,
  },
  {
    id: "fed-p05",
    domain: "federal_requirements",
    stem: "Which recall class is most severe regarding health risk?",
    choices: ["Class I", "Class II", "Class III", "Class IV"],
    correctIndex: 0,
    rationale: "Class I is the most severe health-risk recall class.",
    topicTags: ["recalls"],
    paidOnly: true,
  },
  {
    id: "fed-p06",
    domain: "federal_requirements",
    stem: "A valid prescription for a controlled substance generally requires:",
    choices: ["A legitimate medical purpose and issuance by a DEA-authorized practitioner within legal requirements", "Only a nurse's verbal request without practitioner involvement", "Patient self-certification online", "A technician's signature alone"],
    correctIndex: 0,
    rationale: "Corresponding responsibility and valid practitioner issuance are foundational.",
    topicTags: ["controlled-substances"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "fed-p07",
    domain: "federal_requirements",
    stem: "Which is a HIPAA administrative safeguard concept example?",
    choices: ["Workforce training and access management policies", "Leaving charts in rideshare vehicles", "Public livestream counseling", "Sharing passwords on sticky notes"],
    correctIndex: 0,
    rationale: "Admin safeguards include policies, training, and access management.",
    topicTags: ["HIPAA"],
    paidOnly: true,
  },
  {
    id: "fed-p08",
    domain: "federal_requirements",
    stem: "Transaction information/history/statement concepts in DSCSA relate to:",
    choices: ["Passing tracing data as products move through the supply chain", "Patient counseling scripts", "Technician certification CE", "USP media fill tests"],
    correctIndex: 0,
    rationale: "TI/TH/TS support interoperable tracing.",
    topicTags: ["DSCSA"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "fed-p09",
    domain: "federal_requirements",
    stem: "Which best describes Schedule V relative to Schedule II?",
    choices: ["Lower abuse potential relative ranking than Schedule II, with accepted medical use", "Higher abuse potential than Schedule I", "No medical use", "Identical refill rules to CII always"],
    correctIndex: 0,
    rationale: "Schedule V has lower relative abuse potential than II through IV.",
    topicTags: ["schedules"],
    paidOnly: true,
  },
  {
    id: "fed-p10",
    domain: "federal_requirements",
    stem: "Patient authorization is generally needed before:",
    choices: ["Disclosing PHI for marketing unrelated to treatment/payment/operations", "Submitting claims for treatment payment", "Sharing PHI among treatment team members for care", "Filling a prescription presented by the patient"],
    correctIndex: 0,
    rationale: "Marketing disclosures often need authorization; TPO has pathways.",
    topicTags: ["HIPAA"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "fed-p11",
    domain: "federal_requirements",
    stem: "Which agency is primarily associated with drug recalls in the US?",
    choices: ["FDA", "DEA only", "FCC", "USP Convention as a regulatory enforcer"],
    correctIndex: 0,
    rationale: "FDA leads drug recall classification/oversight.",
    topicTags: ["recalls", "FDA"],
    paidOnly: true,
  },
  {
    id: "fed-p12",
    domain: "federal_requirements",
    stem: "Federal PSE logbooks generally must capture:",
    choices: ["Purchaser identity elements and product/quantity/date information as required", "Patient diagnosis codes only", "Only the cashier's favorite color", "Physician DEA numbers for OTC sales"],
    correctIndex: 0,
    rationale: "CMEA log elements include ID and transaction details.",
    topicTags: ["pseudoephedrine"],
    paidOnly: true,
  },
  {
    id: "fed-p13",
    domain: "federal_requirements",
    stem: "Corresponding responsibility for controlled prescriptions means:",
    choices: ["Pharmacists share responsibility for ensuring prescriptions are valid/legitimate", "Technicians may ignore red flags if sales are high", "Wholesalers write prescriptions", "Patients set their own schedules"],
    correctIndex: 0,
    rationale: "Corresponding responsibility is a core CSA concept for pharmacists.",
    topicTags: ["controlled-substances"],
    paidOnly: true,
  },
  {
    id: "fed-p14",
    domain: "federal_requirements",
    stem: "Which is NOT an appropriate PHI practice?",
    choices: ["Discussing a famous patient's therapy with the media for publicity", "Using encrypted email per policy", "Verifying caller identity", "Need-to-know access for staff"],
    correctIndex: 0,
    rationale: "Media disclosures of PHI without authorization are improper.",
    topicTags: ["HIPAA"],
    paidOnly: true,
  },
  {
    id: "fed-p15",
    domain: "federal_requirements",
    stem: "Stolen prescription bottles found in the supply chain should be treated under DSCSA concepts as potentially:",
    choices: ["Illegitimate / suspect and handled per investigation procedures", "Ordinary overstock", "Marketing samples", "Non-recall Class IV"],
    correctIndex: 0,
    rationale: "Stolen product is a classic illegitimate category.",
    topicTags: ["DSCSA"],
    paidOnly: true,
  },
  {
    id: "fed-p16",
    domain: "federal_requirements",
    stem: "Which statement about CII prescriptions is generally true federally?",
    choices: ["Refills are not permitted in the same way as noncontrols; issuance/partial fill rules are specialized", "They may have unlimited refills for 1 year always", "They are OTC with ID", "They never require a prescription"],
    correctIndex: 0,
    rationale: "CIIs have strict refill/issuance rules.",
    topicTags: ["controlled-substances"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "fed-p17",
    domain: "federal_requirements",
    stem: "A notice of privacy practices is associated with:",
    choices: ["HIPAA transparency about how PHI is used and disclosed", "DEA Form 106 only", "DSCSA serialization barcodes", "USP <797> air changes"],
    correctIndex: 0,
    rationale: "NPPs inform patients about PHI practices.",
    topicTags: ["HIPAA"],
    paidOnly: true,
  },
  {
    id: "fed-p18",
    domain: "federal_requirements",
    stem: "Which best matches Class II recall risk language?",
    choices: ["Temporary or medically reversible adverse consequences; serious harm remote", "No risk wording exists for Class II", "Always fatal", "Only applies to devices, never drugs"],
    correctIndex: 0,
    rationale: "Standard Class II definition.",
    topicTags: ["recalls"],
    paidOnly: true,
  },
  {
    id: "fed-p19",
    domain: "federal_requirements",
    stem: "Pharmacy theft of controlled substances generally requires:",
    choices: ["Reporting per DEA/federal and policy requirements (e.g., significant loss pathways)", "No reporting if under $5", "Only a social media post", "Waiting 1 year before any report"],
    correctIndex: 0,
    rationale: "Significant loss/theft has DEA reporting expectations.",
    topicTags: ["DEA"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "fed-p20",
    domain: "federal_requirements",
    stem: "Which identifier is most directly a drug product packaging code concept used in the US?",
    choices: ["NDC", "VIN", "ISBN", "SSN"],
    correctIndex: 0,
    rationale: "National Drug Code identifies labeler/product/package.",
    topicTags: ["NDC"],
    paidOnly: true,
  },
  {
    id: "fed-p21",
    domain: "federal_requirements",
    stem: "Minimum necessary does NOT typically require:",
    choices: ["Refusing to use any PHI even when needed for dispensing", "Limiting chart access by role", "Avoiding hallway PHI gossip", "Redacting extra pages when faxing to a payer if policy says so"],
    correctIndex: 0,
    rationale: "Minimum necessary still allows needed PHI for treatment/payment/operations.",
    topicTags: ["HIPAA"],
    paidOnly: true,
  },
  {
    id: "fed-p22",
    domain: "federal_requirements",
    stem: "Which is a federal agency primarily enforcing controlled substance laws?",
    choices: ["DEA", "FTC for all CSA schedules", "Postal Service as sole CSA enforcer", "Local school boards"],
    correctIndex: 0,
    rationale: "DEA enforces the CSA.",
    topicTags: ["DEA"],
    paidOnly: true,
  }
];
