import type { Question } from "./types";

export const MEDICATIONS_QUESTIONS: Question[] = [
  {
    id: "med-001",
    domain: "medications",
    stem: "A prescription is written for atorvastatin. Which brand name matches this generic?",
    choices: ["Lipitor", "Zocor", "Crestor", "Pravachol"],
    correctIndex: 0,
    rationale: "Atorvastatin is the generic for Lipitor. Zocor is simvastatin, Crestor is rosuvastatin, Pravachol is pravastatin.",
    topicTags: ["brand-generic", "statins"],
  },
  {
    id: "med-002",
    domain: "medications",
    stem: "Which generic corresponds to the brand name Synthroid?",
    choices: ["levothyroxine", "liothyronine", "methimazole", "propylthiouracil"],
    correctIndex: 0,
    rationale: "Synthroid is a brand of levothyroxine. Liothyronine is Cytomel; methimazole and PTU are antithyroid agents.",
    topicTags: ["brand-generic", "thyroid"],
  },
  {
    id: "med-003",
    domain: "medications",
    stem: "Metformin is most commonly classified in which therapeutic category?",
    choices: ["Biguanide antidiabetic", "Sulfonylurea", "GLP-1 receptor agonist", "DPP-4 inhibitor"],
    correctIndex: 0,
    rationale: "Metformin is a biguanide used for type 2 diabetes.",
    topicTags: ["therapeutic-class", "diabetes"],
  },
  {
    id: "med-004",
    domain: "medications",
    stem: "Which medication is a high-alert anticoagulant commonly dispensed as a vitamin K antagonist?",
    choices: ["warfarin", "clopidogrel", "aspirin", "enoxaparin"],
    correctIndex: 0,
    rationale: "Warfarin is a vitamin K antagonist and high-alert anticoagulant. Clopidogrel and aspirin are antiplatelets; enoxaparin is an LMWH.",
    topicTags: ["high-alert", "anticoagulant"],
    needsReview: true,
  },
  {
    id: "med-005",
    domain: "medications",
    stem: "Lisinopril belongs to which drug class?",
    choices: ["ACE inhibitor", "ARB", "Beta blocker", "Calcium channel blocker"],
    correctIndex: 0,
    rationale: "Lisinopril is an ACE inhibitor.",
    topicTags: ["therapeutic-class", "cardiovascular"],
  },
  {
    id: "med-006",
    domain: "medications",
    stem: "Which controlled substance schedule typically includes drugs with accepted medical use and the highest abuse potential among scheduled prescription drugs (e.g., oxycodone products)?",
    choices: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"],
    correctIndex: 0,
    rationale: "Schedule II includes many potent opioids with accepted medical use and high abuse potential.",
    topicTags: ["schedules", "controlled-substances"],
  },
  {
    id: "med-007",
    domain: "medications",
    stem: "Alprazolam is generally placed in which controlled substance schedule under federal law?",
    choices: ["Schedule IV", "Schedule II", "Schedule III", "Schedule V"],
    correctIndex: 0,
    rationale: "Benzodiazepines such as alprazolam are Schedule IV federally.",
    topicTags: ["schedules", "benzodiazepines"],
  },
  {
    id: "med-008",
    domain: "medications",
    stem: "Which brand name matches the generic amlodipine?",
    choices: ["Norvasc", "Lopressor", "Coreg", "Diovan"],
    correctIndex: 0,
    rationale: "Amlodipine is Norvasc.",
    topicTags: ["brand-generic", "cardiovascular"],
  },
  {
    id: "med-009",
    domain: "medications",
    stem: "Omeprazole is primarily used to treat which condition category?",
    choices: ["Acid-related disorders (e.g., GERD)", "Bacterial skin infections", "Type 1 diabetes", "Acute gout flares"],
    correctIndex: 0,
    rationale: "Omeprazole is a proton pump inhibitor used for GERD and related acid disorders.",
    topicTags: ["indications", "PPI"],
  },
  {
    id: "med-010",
    domain: "medications",
    stem: "Which medication is an SSRI antidepressant often known by the brand Zoloft?",
    choices: ["sertraline", "fluoxetine", "paroxetine", "citalopram"],
    correctIndex: 0,
    rationale: "Zoloft is sertraline.",
    topicTags: ["brand-generic", "antidepressants"],
  },
  {
    id: "med-011",
    domain: "medications",
    stem: "Insulin products are considered high-alert primarily because:",
    choices: ["Dosing errors can cause severe hypoglycemia or hyperglycemia", "They are always Schedule II controlled substances", "They must be dispensed only in unit-dose cups", "They have no brand-generic equivalents"],
    correctIndex: 0,
    rationale: "Insulins are high-alert due to risk of serious harm from dosing and product mix-ups.",
    topicTags: ["high-alert", "insulin", "diabetes"],
  },
  {
    id: "med-012",
    domain: "medications",
    stem: "Gabapentin is commonly used for which of the following?",
    choices: ["Neuropathic pain and certain seizure disorders", "Acute bacterial meningitis first-line monotherapy", "Thrombolysis in stroke", "Vitamin B12 deficiency"],
    correctIndex: 0,
    rationale: "Gabapentin is used for neuropathic pain and as adjunctive therapy for some seizures.",
    topicTags: ["indications", "neurology"],
    needsReview: true,
  },
  {
    id: "med-013",
    domain: "medications",
    stem: "Which generic matches the brand name Glucophage?",
    choices: ["metformin", "glipizide", "glyburide", "pioglitazone"],
    correctIndex: 0,
    rationale: "Glucophage is metformin.",
    topicTags: ["brand-generic", "diabetes"],
  },
  {
    id: "med-014",
    domain: "medications",
    stem: "Hydrocodone combination products are federally classified as:",
    choices: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"],
    correctIndex: 0,
    rationale: "Hydrocodone combination products are Schedule II under federal law.",
    topicTags: ["schedules", "opioids"],
  },
  {
    id: "med-015",
    domain: "medications",
    stem: "Montelukast (Singulair) is primarily indicated for:",
    choices: ["Asthma and allergic rhinitis management", "Acute hypertensive emergency", "Clostridium difficile infection", "Opioid withdrawal"],
    correctIndex: 0,
    rationale: "Montelukast is a leukotriene receptor antagonist used for asthma and allergic rhinitis.",
    topicTags: ["indications", "respiratory"],
  },
  {
    id: "med-016",
    domain: "medications",
    stem: "Which drug is a loop diuretic commonly branded as Lasix?",
    choices: ["furosemide", "hydrochlorothiazide", "spironolactone", "chlorthalidone"],
    correctIndex: 0,
    rationale: "Lasix is furosemide, a loop diuretic.",
    topicTags: ["brand-generic", "diuretics"],
  },
  {
    id: "med-017",
    domain: "medications",
    stem: "Pregabalin (Lyrica) is federally scheduled as:",
    choices: ["Schedule V", "Schedule II", "Schedule III", "Schedule I"],
    correctIndex: 0,
    rationale: "Pregabalin is Schedule V federally.",
    topicTags: ["schedules", "neurology"],
  },
  {
    id: "med-018",
    domain: "medications",
    stem: "What is the primary purpose of a REMS program?",
    choices: ["To manage known or potential serious risks of certain medications while keeping them available", "To set AWP pricing for wholesalers", "To replace the need for a valid prescription", "To authorize technicians to prescribe controlled substances"],
    correctIndex: 0,
    rationale: "REMS programs manage serious risks for specific drugs.",
    topicTags: ["REMS", "federal-med-safety"],
  },
  {
    id: "med-019",
    domain: "medications",
    stem: "Clopidogrel is best described as:",
    choices: ["An antiplatelet agent", "A direct oral anticoagulant (DOAC)", "A low molecular weight heparin", "A vitamin K antagonist"],
    correctIndex: 0,
    rationale: "Clopidogrel (Plavix) is an antiplatelet P2Y12 inhibitor.",
    topicTags: ["therapeutic-class", "cardiovascular"],
  },
  {
    id: "med-020",
    domain: "medications",
    stem: "Which medication is commonly used as a short-acting beta agonist rescue inhaler component?",
    choices: ["albuterol", "tiotropium", "fluticasone alone as rescue", "montelukast"],
    correctIndex: 0,
    rationale: "Albuterol is a SABA used for rescue.",
    topicTags: ["respiratory", "dosage-forms"],
  },
  {
    id: "med-021",
    domain: "medications",
    stem: "Levothyroxine counseling often emphasizes taking the dose:",
    choices: ["On an empty stomach, consistently, away from interacting supplements like calcium/iron", "Only with a high-fat meal", "Only at bedtime with milk", "Crushed and mixed into grapefruit juice"],
    correctIndex: 0,
    rationale: "Absorption is affected by food and polyvalent cations; consistent empty-stomach timing is standard counseling.",
    topicTags: ["counseling", "thyroid"],
    needsReview: true,
  },
  {
    id: "med-022",
    domain: "medications",
    stem: "Which antibiotic class includes azithromycin?",
    choices: ["Macrolides", "Fluoroquinolones", "Cephalosporins", "Tetracyclines"],
    correctIndex: 0,
    rationale: "Azithromycin is a macrolide.",
    topicTags: ["therapeutic-class", "antibiotics"],
  },
  {
    id: "med-023",
    domain: "medications",
    stem: "Tramadol is federally classified as:",
    choices: ["Schedule IV", "Schedule II", "Schedule III", "Unscheduled"],
    correctIndex: 0,
    rationale: "Tramadol is Schedule IV under federal law.",
    topicTags: ["schedules", "opioids"],
  },
  {
    id: "med-024",
    domain: "medications",
    stem: "Losartan belongs to which class?",
    choices: ["Angiotensin II receptor blocker (ARB)", "ACE inhibitor", "Alpha-1 blocker", "Nitrate"],
    correctIndex: 0,
    rationale: "Losartan is an ARB.",
    topicTags: ["therapeutic-class", "cardiovascular"],
  },
  {
    id: "med-025",
    domain: "medications",
    stem: "Which medication is a proton pump inhibitor?",
    choices: ["pantoprazole", "sucralfate", "metoclopramide", "calcium carbonate only"],
    correctIndex: 0,
    rationale: "Pantoprazole is a PPI.",
    topicTags: ["therapeutic-class", "GI"],
  },
  {
    id: "med-026",
    domain: "medications",
    stem: "Amphetamine mixed salts (e.g., Adderall) are typically:",
    choices: ["Schedule II", "Schedule III", "Schedule IV", "Schedule V"],
    correctIndex: 0,
    rationale: "Amphetamine products used for ADHD are Schedule II.",
    topicTags: ["schedules", "CNS-stimulants"],
  },
  {
    id: "med-027",
    domain: "medications",
    stem: "Which brand matches generic escitalopram?",
    choices: ["Lexapro", "Prozac", "Effexor", "Wellbutrin"],
    correctIndex: 0,
    rationale: "Lexapro is escitalopram.",
    topicTags: ["brand-generic", "antidepressants"],
  },
  {
    id: "med-028",
    domain: "medications",
    stem: "Potassium chloride oral solutions/tablets are high-alert in many settings because:",
    choices: ["Incorrect dosing or route confusion can cause serious cardiac harm", "They are Schedule I substances", "They must be refrigerated after every open", "They have no NDC numbers"],
    correctIndex: 0,
    rationale: "Concentrated potassium products are high-alert due to risk of severe harm from dosing/route errors.",
    topicTags: ["high-alert", "electrolytes"],
  },
  {
    id: "med-029",
    domain: "medications",
    stem: "Duloxetine (Cymbalta) is commonly used for:",
    choices: ["Depression and certain neuropathic pain conditions", "Acute gout only", "Vitamin D deficiency", "Helicobacter pylori monotherapy"],
    correctIndex: 0,
    rationale: "Duloxetine is an SNRI used for MDD and approved neuropathic/pain indications.",
    topicTags: ["indications", "antidepressants"],
    needsReview: true,
  },
  {
    id: "med-030",
    domain: "medications",
    stem: "Which medication is an HMG-CoA reductase inhibitor (statin)?",
    choices: ["rosuvastatin", "ezetimibe", "fenofibrate", "cholestyramine"],
    correctIndex: 0,
    rationale: "Rosuvastatin is a statin.",
    topicTags: ["therapeutic-class", "statins"],
  },
  {
    id: "med-031",
    domain: "medications",
    stem: "Carvedilol is best classified as:",
    choices: ["A nonselective beta blocker with alpha-blocking activity", "An ACE inhibitor", "A thiazide diuretic", "A DOAC"],
    correctIndex: 0,
    rationale: "Carvedilol blocks beta and alpha-1 receptors.",
    topicTags: ["therapeutic-class", "cardiovascular"],
  },
  {
    id: "med-032",
    domain: "medications",
    stem: "Which dosage form is designed for placement under the tongue for rapid absorption?",
    choices: ["Sublingual tablet", "Enteric-coated tablet", "Transdermal patch", "Rectal enema"],
    correctIndex: 0,
    rationale: "Sublingual tablets dissolve under the tongue for transmucosal absorption.",
    topicTags: ["dosage-forms"],
  },
  {
    id: "med-033",
    domain: "medications",
    stem: "Methylphenidate products used for ADHD are generally:",
    choices: ["Schedule II", "Schedule IV", "Schedule V", "Not controlled"],
    correctIndex: 0,
    rationale: "Methylphenidate is Schedule II federally.",
    topicTags: ["schedules", "CNS-stimulants"],
  },
  {
    id: "med-034",
    domain: "medications",
    stem: "Apixaban is a:",
    choices: ["Direct oral anticoagulant (factor Xa inhibitor)", "Vitamin K antagonist", "Antiplatelet P2Y12 inhibitor", "Low molecular weight heparin"],
    correctIndex: 0,
    rationale: "Apixaban (Eliquis) is a factor Xa inhibitor DOAC.",
    topicTags: ["anticoagulant", "therapeutic-class"],
    needsReview: true,
  },
  {
    id: "med-035",
    domain: "medications",
    stem: "Which medication is commonly associated with a REMS for teratogenicity risk (isotretinoin programs)?",
    choices: ["isotretinoin", "amoxicillin", "acetaminophen", "loratadine"],
    correctIndex: 0,
    rationale: "Isotretinoin has a well-known REMS/restricted program due to teratogenicity (iPLEDGE).",
    topicTags: ["REMS", "safety"],
  },
  {
    id: "med-p01",
    domain: "medications",
    stem: "Which brand matches generic sitagliptin?",
    choices: ["Januvia", "Invokana", "Farxiga", "Jardiance"],
    correctIndex: 0,
    rationale: "Januvia is sitagliptin (DPP-4).",
    topicTags: ["brand-generic", "diabetes"],
    paidOnly: true,
  },
  {
    id: "med-p02",
    domain: "medications",
    stem: "Bupropion is commonly used for depression and which additional labeled use?",
    choices: ["Smoking cessation (Zyban)", "Acute opioid overdose reversal", "Vitamin K deficiency", "Anthrax prophylaxis"],
    correctIndex: 0,
    rationale: "Bupropion (Zyban) is used for smoking cessation as well as depression.",
    topicTags: ["indications"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p03",
    domain: "medications",
    stem: "Tamsulosin is primarily used for:",
    choices: ["Benign prostatic hyperplasia (BPH) symptoms", "Acute migraine abortion", "Hypothyroidism", "Community-acquired pneumonia"],
    correctIndex: 0,
    rationale: "Tamsulosin is an alpha-1 blocker for BPH.",
    topicTags: ["indications", "urology"],
    paidOnly: true,
  },
  {
    id: "med-p04",
    domain: "medications",
    stem: "Which drug is a cephalosporin antibiotic?",
    choices: ["cephalexin", "azithromycin", "ciprofloxacin", "doxycycline"],
    correctIndex: 0,
    rationale: "Cephalexin is a first-generation cephalosporin.",
    topicTags: ["antibiotics"],
    paidOnly: true,
  },
  {
    id: "med-p05",
    domain: "medications",
    stem: "Zolpidem is federally scheduled as:",
    choices: ["Schedule IV", "Schedule II", "Schedule III", "Schedule I"],
    correctIndex: 0,
    rationale: "Zolpidem (Ambien) is Schedule IV.",
    topicTags: ["schedules", "sedative-hypnotics"],
    paidOnly: true,
  },
  {
    id: "med-p06",
    domain: "medications",
    stem: "Which insulin is typically considered rapid-acting?",
    choices: ["insulin aspart", "insulin glargine", "insulin detemir", "NPH insulin"],
    correctIndex: 0,
    rationale: "Aspart is rapid-acting; glargine/detemir are long-acting; NPH is intermediate.",
    topicTags: ["insulin", "diabetes"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p07",
    domain: "medications",
    stem: "Allopurinol is used primarily to:",
    choices: ["Lower uric acid in gout management", "Treat acute bacterial cystitis", "Reverse heparin", "Treat hypothyroidism"],
    correctIndex: 0,
    rationale: "Allopurinol reduces uric acid production.",
    topicTags: ["indications", "gout"],
    paidOnly: true,
  },
  {
    id: "med-p08",
    domain: "medications",
    stem: "Which brand matches generic valsartan?",
    choices: ["Diovan", "Cozaar", "Benicar", "Avapro"],
    correctIndex: 0,
    rationale: "Diovan is valsartan.",
    topicTags: ["brand-generic"],
    paidOnly: true,
  },
  {
    id: "med-p09",
    domain: "medications",
    stem: "Codeine combination cough products may be scheduled as:",
    choices: ["Schedule III or V depending on formulation and federal/state rules", "Schedule I always", "Schedule II only if OTC", "Never controlled"],
    correctIndex: 0,
    rationale: "Codeine combination products appear in C-III or C-V depending on strength/formulation.",
    topicTags: ["schedules"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p10",
    domain: "medications",
    stem: "Spironolactone is a:",
    choices: ["Potassium-sparing diuretic / aldosterone antagonist", "Loop diuretic", "Thiazide diuretic", "Osmotic diuretic"],
    correctIndex: 0,
    rationale: "Spironolactone antagonizes aldosterone and spares potassium.",
    topicTags: ["diuretics"],
    paidOnly: true,
  },
  {
    id: "med-p11",
    domain: "medications",
    stem: "Which medication is an atypical antipsychotic?",
    choices: ["quetiapine", "sertraline", "lorazepam", "cetirizine"],
    correctIndex: 0,
    rationale: "Quetiapine is an atypical antipsychotic.",
    topicTags: ["psychiatric"],
    paidOnly: true,
  },
  {
    id: "med-p12",
    domain: "medications",
    stem: "Nitroglycerin sublingual tablets are used for:",
    choices: ["Acute angina relief", "Chronic constipation", "Type 2 diabetes first-line", "Bacterial vaginosis"],
    correctIndex: 0,
    rationale: "SL nitroglycerin treats acute anginal episodes.",
    topicTags: ["cardiovascular", "dosage-forms"],
    paidOnly: true,
  },
  {
    id: "med-p13",
    domain: "medications",
    stem: "Which drug is a fluoroquinolone?",
    choices: ["ciprofloxacin", "amoxicillin", "cephalexin", "azithromycin"],
    correctIndex: 0,
    rationale: "Ciprofloxacin is a fluoroquinolone.",
    topicTags: ["antibiotics"],
    paidOnly: true,
  },
  {
    id: "med-p14",
    domain: "medications",
    stem: "Methadone used for opioid use disorder / analgesia is:",
    choices: ["Schedule II", "Schedule IV", "Schedule V", "Not controlled"],
    correctIndex: 0,
    rationale: "Methadone is Schedule II.",
    topicTags: ["schedules", "opioids"],
    paidOnly: true,
  },
  {
    id: "med-p15",
    domain: "medications",
    stem: "Ondansetron is primarily used as:",
    choices: ["An antiemetic (5-HT3 antagonist)", "A stimulant laxative", "An anticonvulsant", "A statin"],
    correctIndex: 0,
    rationale: "Ondansetron blocks 5-HT3 receptors to reduce nausea/vomiting.",
    topicTags: ["GI", "indications"],
    paidOnly: true,
  },
  {
    id: "med-p16",
    domain: "medications",
    stem: "Which brand matches generic fluticasone nasal?",
    choices: ["Flonase", "Nasonex", "Rhinocort", "Astelin"],
    correctIndex: 0,
    rationale: "Flonase is fluticasone.",
    topicTags: ["brand-generic", "respiratory"],
    paidOnly: true,
  },
  {
    id: "med-p17",
    domain: "medications",
    stem: "Diazepam is scheduled as:",
    choices: ["Schedule IV", "Schedule II", "Schedule III", "Schedule V"],
    correctIndex: 0,
    rationale: "Diazepam is Schedule IV.",
    topicTags: ["schedules", "benzodiazepines"],
    paidOnly: true,
  },
  {
    id: "med-p18",
    domain: "medications",
    stem: "Empagliflozin belongs to which class?",
    choices: ["SGLT2 inhibitor", "DPP-4 inhibitor", "Sulfonylurea", "Meglitinide"],
    correctIndex: 0,
    rationale: "Empagliflozin (Jardiance) is an SGLT2 inhibitor.",
    topicTags: ["diabetes", "therapeutic-class"],
    paidOnly: true,
  },
  {
    id: "med-p19",
    domain: "medications",
    stem: "Which medication requires hazardous drug handling awareness in many USP <800> contexts?",
    choices: ["methotrexate (certain uses)", "polyethylene glycol 3350 OTC", "artificial tears", "normal saline irrigation"],
    correctIndex: 0,
    rationale: "Methotrexate is commonly on hazardous drug lists depending on use/form.",
    topicTags: ["hazardous-drugs", "safety"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p20",
    domain: "medications",
    stem: "Atenolol is a:",
    choices: ["Beta blocker", "ACE inhibitor", "ARB", "CCB"],
    correctIndex: 0,
    rationale: "Atenolol is a beta-1 selective blocker.",
    topicTags: ["cardiovascular"],
    paidOnly: true,
  },
  {
    id: "med-p21",
    domain: "medications",
    stem: "Which is an example of a Schedule III controlled substance category under federal law?",
    choices: ["Certain anabolic steroids and some codeine combination products", "Heroin", "Alprazolam", "Pregabalin"],
    correctIndex: 0,
    rationale: "Schedule III includes anabolic steroids and specified codeine combos.",
    topicTags: ["schedules"],
    paidOnly: true,
  },
  {
    id: "med-p22",
    domain: "medications",
    stem: "Rivaroxaban is a:",
    choices: ["Factor Xa inhibitor DOAC", "Vitamin K antagonist", "Antiplatelet", "Heparin"],
    correctIndex: 0,
    rationale: "Rivaroxaban (Xarelto) inhibits factor Xa.",
    topicTags: ["anticoagulant"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p23",
    domain: "medications",
    stem: "Which brand matches generic rosuvastatin?",
    choices: ["Crestor", "Lipitor", "Zocor", "Mevacor"],
    correctIndex: 0,
    rationale: "Crestor is rosuvastatin.",
    topicTags: ["brand-generic", "statins"],
    paidOnly: true,
  },
  {
    id: "med-p24",
    domain: "medications",
    stem: "Topiramate is commonly used for:",
    choices: ["Seizure disorders and migraine prevention", "Acute gout flare only", "OTC allergy relief", "Vitamin C deficiency"],
    correctIndex: 0,
    rationale: "Topiramate has anticonvulsant and migraine prophylaxis uses.",
    topicTags: ["neurology"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "med-p25",
    domain: "medications",
    stem: "Which statement about Schedule I drugs is correct?",
    choices: ["They have no currently accepted medical use federally and high abuse potential", "They are OTC cough syrups", "They may be prescribed like Schedule II with refills", "They include alprazolam"],
    correctIndex: 0,
    rationale: "Schedule I agents lack accepted medical use under federal CSA framing.",
    topicTags: ["schedules"],
    paidOnly: true,
  },
  {
    id: "med-p26",
    domain: "medications",
    stem: "Buspirone is primarily used for:",
    choices: ["Anxiety", "Acute bacterial sinusitis", "Hyperlipidemia", "Insomnia as a Z-drug"],
    correctIndex: 0,
    rationale: "Buspirone is an anxiolytic (not a benzodiazepine).",
    topicTags: ["psychiatric"],
    paidOnly: true,
  },
  {
    id: "med-p27",
    domain: "medications",
    stem: "Which medication is a calcium channel blocker?",
    choices: ["amlodipine", "lisinopril", "losartan", "metoprolol"],
    correctIndex: 0,
    rationale: "Amlodipine is a dihydropyridine CCB.",
    topicTags: ["cardiovascular"],
    paidOnly: true,
  },
  {
    id: "med-p28",
    domain: "medications",
    stem: "Finasteride is commonly used for:",
    choices: ["BPH and male pattern hair loss (indication-specific products)", "Acute asthma exacerbation", "Hypokalemia", "Opioid reversal"],
    correctIndex: 0,
    rationale: "Finasteride inhibits 5-alpha reductase for BPH/alopecia products.",
    topicTags: ["urology"],
    paidOnly: true,
    needsReview: true,
  }
];
