import type { Question } from "./types";

export const ORDER_QUESTIONS: Question[] = [
  {
    id: "ord-001",
    domain: "order_entry",
    stem: "The sig '1 tab po bid' most nearly means:",
    choices: ["Take one tablet by mouth twice daily", "Take one tablet by mouth at bedtime", "Instill one tablet in each eye daily", "Take one tablespoon twice daily"],
    correctIndex: 0,
    rationale: "po = by mouth; bid = twice daily.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-002",
    domain: "order_entry",
    stem: "A patient receives 30 tablets with directions: 1 tablet by mouth twice daily. Days supply is:",
    choices: ["15 days", "30 days", "60 days", "7 days"],
    correctIndex: 0,
    rationale: "2 tablets/day; 30 tablets / 2 = 15 days.",
    topicTags: ["days-supply", "calculations"],
  },
  {
    id: "ord-003",
    domain: "order_entry",
    stem: "An NDC typically encodes which concepts?",
    choices: ["Labeler, product, and package codes", "Patient MRN, NPI, and DEA only", "Only the AWP and WAC", "Only the lot number"],
    correctIndex: 0,
    rationale: "NDC segments identify labeler, product, and package size.",
    topicTags: ["NDC"],
  },
  {
    id: "ord-004",
    domain: "order_entry",
    stem: "The abbreviation 'prn' means:",
    choices: ["As needed", "Every morning", "Before meals", "Right eye"],
    correctIndex: 0,
    rationale: "prn = pro re nata = as needed.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-005",
    domain: "order_entry",
    stem: "A prescription for amoxicillin 250 mg/5 mL: give 5 mL po tid x 10 days. How many mL should be dispensed?",
    choices: ["150 mL", "50 mL", "100 mL", "200 mL"],
    correctIndex: 0,
    rationale: "5 mL x 3 times/day x 10 days = 150 mL.",
    topicTags: ["calculations", "days-supply"],
  },
  {
    id: "ord-006",
    domain: "order_entry",
    stem: "'gtt' in a sig usually means:",
    choices: ["Drop", "Gram", "Tablet", "Capsule"],
    correctIndex: 0,
    rationale: "gtt = gutta/guttae = drop(s).",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-007",
    domain: "order_entry",
    stem: "A patient takes 1 tablet every 6 hours around the clock. Tablets needed for 30 days are:",
    choices: ["120", "30", "60", "90"],
    correctIndex: 0,
    rationale: "24/6 = 4 doses/day; 4 x 30 = 120 tablets.",
    topicTags: ["calculations", "days-supply"],
  },
  {
    id: "ord-008",
    domain: "order_entry",
    stem: "'od' as a traditional sig abbreviation most commonly means:",
    choices: ["Right eye", "Both ears", "Left ear", "By mouth"],
    correctIndex: 0,
    rationale: "od = oculus dexter = right eye (modern practice prefers plain language).",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-009",
    domain: "order_entry",
    stem: "If a cream is applied twice daily and a 60 g tube lasts the patient 30 days at that rate, approximate daily use is:",
    choices: ["2 g/day", "1 g/day", "5 g/day", "10 g/day"],
    correctIndex: 0,
    rationale: "60 g / 30 days = 2 g/day.",
    topicTags: ["calculations", "days-supply"],
  },
  {
    id: "ord-010",
    domain: "order_entry",
    stem: "Which claim rejection concept means the drug is not covered under the plan's formulary (general awareness)?",
    choices: ["Non-formulary / product not covered style reject", "Wrong days supply always coded as refill too soon only", "NDC not found meaning patient deceased", "Prior auth approved"],
    correctIndex: 0,
    rationale: "Non-formulary rejects indicate coverage/formulary issues.",
    topicTags: ["insurance"],
  },
  {
    id: "ord-011",
    domain: "order_entry",
    stem: "'ac' means:",
    choices: ["Before meals", "After meals", "At bedtime", "Right ear"],
    correctIndex: 0,
    rationale: "ac = ante cibum = before meals.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-012",
    domain: "order_entry",
    stem: "Doctor orders 500 mg; stock is 250 mg tablets. Tablets per dose:",
    choices: ["2", "1", "4", "0.5"],
    correctIndex: 0,
    rationale: "500/250 = 2 tablets.",
    topicTags: ["calculations"],
  },
  {
    id: "ord-013",
    domain: "order_entry",
    stem: "A 10 mL vial contains 100 mg/mL. How many mg in 2.5 mL?",
    choices: ["250 mg", "100 mg", "25 mg", "1000 mg"],
    correctIndex: 0,
    rationale: "100 mg/mL x 2.5 mL = 250 mg.",
    topicTags: ["calculations"],
  },
  {
    id: "ord-014",
    domain: "order_entry",
    stem: "'hs' traditionally means:",
    choices: ["At bedtime", "Every hour", "Left eye", "As directed"],
    correctIndex: 0,
    rationale: "hs = hora somni = at bedtime.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-015",
    domain: "order_entry",
    stem: "Days supply for 90 capsules, 1 cap po tid:",
    choices: ["30 days", "90 days", "45 days", "15 days"],
    correctIndex: 0,
    rationale: "3 capsules/day; 90/3 = 30 days.",
    topicTags: ["days-supply", "calculations"],
  },
  {
    id: "ord-016",
    domain: "order_entry",
    stem: "Which best describes a refill-too-soon rejection?",
    choices: ["The plan believes insufficient time has elapsed based on prior fill days supply", "The NDC is invalid", "The patient name mismatches always", "The drug is Schedule I"],
    correctIndex: 0,
    rationale: "Refill-too-soon is a timing/adjudication issue.",
    topicTags: ["insurance"],
  },
  {
    id: "ord-017",
    domain: "order_entry",
    stem: "Convert 1 teaspoonful (using common pharmacy conversion) to mL:",
    choices: ["5 mL", "15 mL", "30 mL", "1 mL"],
    correctIndex: 0,
    rationale: "1 tsp = 5 mL in common pharmacy conversions.",
    topicTags: ["calculations"],
  },
  {
    id: "ord-018",
    domain: "order_entry",
    stem: "'os' traditionally means:",
    choices: ["Left eye", "Right eye", "Both ears", "By mouth"],
    correctIndex: 0,
    rationale: "os = oculus sinister = left eye.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-019",
    domain: "order_entry",
    stem: "A prescription written for 1 tablet daily has 2 refills authorized for a noncontrolled drug. Including the original fill, maximum fills indicated are:",
    choices: ["3", "2", "1", "4"],
    correctIndex: 0,
    rationale: "Original + 2 refills = 3 total fills if all used.",
    topicTags: ["refills"],
  },
  {
    id: "ord-020",
    domain: "order_entry",
    stem: "Weight-based dose: 10 mg/kg for a 20 kg child. Total dose:",
    choices: ["200 mg", "20 mg", "10 mg", "2 mg"],
    correctIndex: 0,
    rationale: "10 mg/kg x 20 kg = 200 mg.",
    topicTags: ["calculations"],
  },
  {
    id: "ord-021",
    domain: "order_entry",
    stem: "'ou' traditionally means:",
    choices: ["Both eyes", "Right ear", "Left ear", "Each nostril only"],
    correctIndex: 0,
    rationale: "ou = oculus uterque = both eyes.",
    topicTags: ["sig-codes"],
  },
  {
    id: "ord-022",
    domain: "order_entry",
    stem: "How many 5 mg tablets are needed for a total daily dose of 20 mg given as equal doses twice daily for 14 days?",
    choices: ["56", "28", "14", "112"],
    correctIndex: 0,
    rationale: "20 mg/day = 4 tablets/day of 5 mg; 4 x 14 = 56.",
    topicTags: ["calculations", "days-supply"],
  },
  {
    id: "ord-p01",
    domain: "order_entry",
    stem: "'pc' means:",
    choices: ["After meals", "Before meals", "At bedtime", "Each ear"],
    correctIndex: 0,
    rationale: "pc = post cibum = after meals.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p02",
    domain: "order_entry",
    stem: "Days supply for 120 mL, 5 mL po bid:",
    choices: ["12 days", "24 days", "10 days", "30 days"],
    correctIndex: 0,
    rationale: "10 mL/day; 120/10 = 12 days.",
    topicTags: ["days-supply", "calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p03",
    domain: "order_entry",
    stem: "1 tablespoon (common pharmacy conversion) equals:",
    choices: ["15 mL", "5 mL", "30 mL", "3 mL"],
    correctIndex: 0,
    rationale: "1 tbsp = 15 mL.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p04",
    domain: "order_entry",
    stem: "'au' traditionally means:",
    choices: ["Both ears", "Both eyes", "Left eye", "Right eye"],
    correctIndex: 0,
    rationale: "au = auris uterque = both ears.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p05",
    domain: "order_entry",
    stem: "Stock solution is 20 mg/mL; needed dose is 40 mg. Volume to draw:",
    choices: ["2 mL", "0.5 mL", "4 mL", "20 mL"],
    correctIndex: 0,
    rationale: "40/20 = 2 mL.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p06",
    domain: "order_entry",
    stem: "Which NDC segment typically identifies the manufacturer/labeler?",
    choices: ["The first segment (labeler code)", "The patient's ZIP code", "The DEA schedule number alone", "The claim authorization number"],
    correctIndex: 0,
    rationale: "Labeler code is the first NDC segment.",
    topicTags: ["NDC"],
    paidOnly: true,
  },
  {
    id: "ord-p07",
    domain: "order_entry",
    stem: "'qid' means:",
    choices: ["Four times daily", "Every other day", "Once weekly", "Every hour"],
    correctIndex: 0,
    rationale: "qid = four times daily.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p08",
    domain: "order_entry",
    stem: "A 30-day supply of a drug taken once daily is transferred early at day 10 for vacation. Which statement is most accurate at a general tech level?",
    choices: ["Plan rules and pharmacy policy determine early fill eligibility; adjudication may reject refill-too-soon", "Federal law always bans any early fill for all drugs", "Technicians may override any payer rule without pharmacist", "Days supply math is irrelevant to rejects"],
    correctIndex: 0,
    rationale: "Early fills depend on payer rules and policy.",
    topicTags: ["insurance", "refills"],
    paidOnly: true,
  },
  {
    id: "ord-p09",
    domain: "order_entry",
    stem: "Percent strength 5% w/v means:",
    choices: ["5 g of drug per 100 mL of solution", "5 mg per 5 mL only", "5 mL per 100 g always", "50 g per mL"],
    correctIndex: 0,
    rationale: "% w/v is grams per 100 mL.",
    topicTags: ["calculations"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "ord-p10",
    domain: "order_entry",
    stem: "How many grams of drug in 200 mL of a 5% w/v solution?",
    choices: ["10 g", "5 g", "1 g", "20 g"],
    correctIndex: 0,
    rationale: "5 g/100 mL => 10 g in 200 mL.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p11",
    domain: "order_entry",
    stem: "'ad' traditionally means:",
    choices: ["Right ear", "Left ear", "Both eyes", "Right eye"],
    correctIndex: 0,
    rationale: "ad = auris dextra = right ear.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p12",
    domain: "order_entry",
    stem: "Ratio strength 1:1000 as a percent is:",
    choices: ["0.1%", "1%", "10%", "0.01%"],
    correctIndex: 0,
    rationale: "1/1000 = 0.001 = 0.1%.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p13",
    domain: "order_entry",
    stem: "If directions are 2 puffs inhaled q6h, puffs per day (around the clock):",
    choices: ["8", "2", "4", "6"],
    correctIndex: 0,
    rationale: "24/6 = 4 dosing times x 2 puffs = 8.",
    topicTags: ["calculations", "sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p14",
    domain: "order_entry",
    stem: "'as' traditionally means:",
    choices: ["Left ear", "Right ear", "Both eyes", "Left eye"],
    correctIndex: 0,
    rationale: "as = auris sinistra = left ear.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p15",
    domain: "order_entry",
    stem: "IV flow: 1000 mL over 8 hours. mL/hour rate:",
    choices: ["125 mL/hr", "100 mL/hr", "80 mL/hr", "250 mL/hr"],
    correctIndex: 0,
    rationale: "1000/8 = 125 mL/hr.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p16",
    domain: "order_entry",
    stem: "A prior authorization reject generally means:",
    choices: ["The plan requires additional approval before covering the product", "The pharmacy NDC database is offline forever", "The patient must pay cash only always without options", "The drug is Schedule I"],
    correctIndex: 0,
    rationale: "PA rejects require plan approval workflows.",
    topicTags: ["insurance"],
    paidOnly: true,
  },
  {
    id: "ord-p17",
    domain: "order_entry",
    stem: "Days supply for 1 inhaler with 200 actuations, 2 puffs bid:",
    choices: ["50 days", "100 days", "25 days", "200 days"],
    correctIndex: 0,
    rationale: "4 puffs/day; 200/4 = 50 days.",
    topicTags: ["days-supply", "calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p18",
    domain: "order_entry",
    stem: "'stat' means:",
    choices: ["Immediately", "Weekly", "Monthly", "As needed only"],
    correctIndex: 0,
    rationale: "stat = immediately.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p19",
    domain: "order_entry",
    stem: "Convert 0.5 g to mg:",
    choices: ["500 mg", "50 mg", "5 mg", "5000 mg"],
    correctIndex: 0,
    rationale: "1 g = 1000 mg; 0.5 g = 500 mg.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p20",
    domain: "order_entry",
    stem: "Which best describes package size selection during product choice?",
    choices: ["Match the ordered quantity/NDC package appropriately while checking strength and form", "Always pick the largest bottle regardless of Rx", "Ignore NDC package codes", "Choose based on bottle color only"],
    correctIndex: 0,
    rationale: "Correct package/strength/form selection is core order processing.",
    topicTags: ["NDC", "error-prevention"],
    paidOnly: true,
  },
  {
    id: "ord-p21",
    domain: "order_entry",
    stem: "Dose is 7.5 mg; tablets are 2.5 mg. Tablets per dose:",
    choices: ["3", "2", "1", "4"],
    correctIndex: 0,
    rationale: "7.5/2.5 = 3.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p22",
    domain: "order_entry",
    stem: "'ung' traditionally refers to:",
    choices: ["Ointment", "Spray", "Patch", "Capsule"],
    correctIndex: 0,
    rationale: "ung = unguentum = ointment.",
    topicTags: ["sig-codes"],
    paidOnly: true,
  },
  {
    id: "ord-p23",
    domain: "order_entry",
    stem: "A liquid is 125 mg/5 mL. How many mL provide 250 mg?",
    choices: ["10 mL", "5 mL", "2 mL", "15 mL"],
    correctIndex: 0,
    rationale: "125 mg per 5 mL => 250 mg needs 10 mL.",
    topicTags: ["calculations"],
    paidOnly: true,
  },
  {
    id: "ord-p24",
    domain: "order_entry",
    stem: "Which is true about e-prescribing controlled substances at a high level?",
    choices: ["Federal EPCS rules require authentication/security controls beyond ordinary e-Rx", "Any email from a doctor is sufficient", "Paper is banned for all schedules always", "Technicians can approve EPCS enrollment alone"],
    correctIndex: 0,
    rationale: "EPCS has specific security requirements.",
    topicTags: ["controlled-substances", "order-entry"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "ord-p25",
    domain: "order_entry",
    stem: "If a patient uses 1 drop in each eye three times daily from a 5 mL bottle, approximate days supply if 20 drops ≈ 1 mL:",
    choices: ["About 16 days", "About 5 days", "About 50 days", "About 2 days"],
    correctIndex: 0,
    rationale: "6 drops/day; 5 mL x 20 drops/mL = 100 drops; 100/6 ≈ 16.7 days.",
    topicTags: ["calculations", "days-supply"],
    paidOnly: true,
    needsReview: true,
  }
];
