import type { Question } from "./types";

export const SAFETY_QUESTIONS: Question[] = [
  {
    id: "saf-001",
    domain: "patient_safety",
    stem: "Which pair is a classic look-alike/sound-alike (LASA) risk example?",
    choices: ["hydralazine and hydroxyzine", "amoxicillin and acetaminophen", "metformin and montelukast", "ibuprofen and insulin glargine"],
    correctIndex: 0,
    rationale: "Hydralazine and hydroxyzine are frequently cited LASA pair.",
    topicTags: ["LASA", "error-prevention"],
  },
  {
    id: "saf-002",
    domain: "patient_safety",
    stem: "Tall man lettering is primarily used to:",
    choices: ["Differentiate look-alike drug names by capitalizing dissimilar syllables", "Increase font size on all OTC labels only", "Replace barcode scanning", "Indicate Schedule II status"],
    correctIndex: 0,
    rationale: "Tall man lettering highlights differing parts of similar names (e.g., hydrALAZINE vs hydrOXYzine).",
    topicTags: ["LASA", "tall-man"],
  },
  {
    id: "saf-003",
    domain: "patient_safety",
    stem: "Which medication class is commonly on high-alert lists?",
    choices: ["Insulins", "Most topical emollients", "Artificial tears", "Oral rehydration salts"],
    correctIndex: 0,
    rationale: "Insulins are classic high-alert medications.",
    topicTags: ["high-alert"],
  },
  {
    id: "saf-004",
    domain: "patient_safety",
    stem: "Barcode scanning at product selection primarily helps:",
    choices: ["Verify the selected package matches the intended product", "Replace the need for a prescription", "Calculate days supply automatically in all cases", "Satisfy HIPAA training alone"],
    correctIndex: 0,
    rationale: "Barcode verification reduces wrong-drug/wrong-strength selection errors.",
    topicTags: ["error-prevention", "barcode"],
  },
  {
    id: "saf-005",
    domain: "patient_safety",
    stem: "An independent double-check is most appropriate for:",
    choices: ["Certain high-alert preparations where policy requires a second qualified person to verify", "Every OTC candy sale", "Only when the patient requests a coupon", "Shipping non-pharma sundries"],
    correctIndex: 0,
    rationale: "Independent double-checks are a high-alert safety strategy.",
    topicTags: ["high-alert", "error-prevention"],
  },
  {
    id: "saf-006",
    domain: "patient_safety",
    stem: "Which is a near-miss in medication safety language?",
    choices: ["An error that was caught before reaching the patient", "A correctly dispensed prescription", "A paid claim", "A Class III recall only"],
    correctIndex: 0,
    rationale: "Near-misses are intercepted errors valuable for learning systems.",
    topicTags: ["quality", "reporting"],
  },
  {
    id: "saf-007",
    domain: "patient_safety",
    stem: "Which practice reduces LASA errors?",
    choices: ["Separating storage of commonly confused products and using alerts", "Storing all bottles alphabetically by color only", "Removing NDC from labels", "Turning off computer warnings permanently"],
    correctIndex: 0,
    rationale: "Physical separation and system alerts mitigate LASA risk.",
    topicTags: ["LASA", "error-prevention"],
  },
  {
    id: "saf-008",
    domain: "patient_safety",
    stem: "Concentrated electrolyte vials (e.g., potassium chloride for injection concentrate) are high-alert because:",
    choices: ["Wrong dose/route can be fatal", "They are Schedule I", "They lack NDCs", "They are always oral only"],
    correctIndex: 0,
    rationale: "Injectable concentrated electrolytes can cause fatal harm if misused.",
    topicTags: ["high-alert", "electrolytes"],
  },
  {
    id: "saf-009",
    domain: "patient_safety",
    stem: "Which is a quality assurance activity?",
    choices: ["Tracking and trending dispensing error reports to improve processes", "Deleting error logs to improve metrics", "Ignoring recurring near-misses", "Disabling barcode scanners to speed workflow"],
    correctIndex: 0,
    rationale: "QA uses data from errors/near-misses to improve systems.",
    topicTags: ["quality"],
  },
  {
    id: "saf-010",
    domain: "patient_safety",
    stem: "Which pair is another common LASA example?",
    choices: ["clonidine and clonazepam", "lisinopril and losartan only as LASA exclusive pair", "water and saline always", "gloves and gauze"],
    correctIndex: 0,
    rationale: "Clonidine and clonazepam are a known confused name pair.",
    topicTags: ["LASA"],
  },
  {
    id: "saf-011",
    domain: "patient_safety",
    stem: "Hand hygiene in pharmacy operations primarily supports:",
    choices: ["Infection control and product/patient safety", "Faster insurance adjudication", "DSCSA serialization", "DEA Form 222 completion"],
    correctIndex: 0,
    rationale: "Hand hygiene is foundational infection control.",
    topicTags: ["infection-control"],
  },
  {
    id: "saf-012",
    domain: "patient_safety",
    stem: "Which action best prevents wrong-patient errors?",
    choices: ["Using two patient identifiers before dispensing counseling or handoff", "Calling only first names in a busy waiting room", "Skipping DOB checks for regulars", "Using bag tags without verification"],
    correctIndex: 0,
    rationale: "Two identifiers (e.g., name + DOB) reduce wrong-patient events.",
    topicTags: ["error-prevention"],
  },
  {
    id: "saf-013",
    domain: "patient_safety",
    stem: "Chemotherapy agents are high-alert primarily due to:",
    choices: ["Narrow therapeutic index and severe toxicity risk from errors", "Being OTC", "Lacking any labeling", "Never requiring PPE"],
    correctIndex: 0,
    rationale: "Antineoplastics can cause severe harm from dosing/handling errors.",
    topicTags: ["high-alert", "hazardous-drugs"],
  },
  {
    id: "saf-014",
    domain: "patient_safety",
    stem: "Which best describes a root cause analysis goal?",
    choices: ["Identify system factors contributing to an event to prevent recurrence", "Assign maximum personal blame only", "Hide findings from leadership", "Increase speed without process review"],
    correctIndex: 0,
    rationale: "RCA focuses on systems improvement, not solely blame.",
    topicTags: ["quality"],
  },
  {
    id: "saf-015",
    domain: "patient_safety",
    stem: "Using oral syringes that cannot connect to IV lines is an example of:",
    choices: ["A forcing function / device design to prevent wrong-route errors", "A HIPAA safeguard", "A DSCSA tracing tool", "A Schedule V requirement"],
    correctIndex: 0,
    rationale: "Incompatibility of oral syringes with IV ports prevents accidental IV administration of oral liquids.",
    topicTags: ["error-prevention", "high-alert"],
  },
  {
    id: "saf-016",
    domain: "patient_safety",
    stem: "Which is appropriate when a dispensing error reaches a patient?",
    choices: ["Follow pharmacy policy for disclosure, documentation, and clinical follow-up with pharmacist involvement", "Delete the profile and deny it occurred", "Ask the patient to post on social media first", "Ignore if the drug was inexpensive"],
    correctIndex: 0,
    rationale: "Error response requires policy-based disclosure and documentation.",
    topicTags: ["quality", "reporting"],
  },
  {
    id: "saf-017",
    domain: "patient_safety",
    stem: "Look-alike packaging risk is reduced by:",
    choices: ["Careful stock checks and avoiding adjacent storage of confusing packages", "Turning bottles upside down randomly", "Removing barcodes", "Printing labels without drug names"],
    correctIndex: 0,
    rationale: "Packaging similarity contributes to selection errors; storage and verification help.",
    topicTags: ["LASA", "error-prevention"],
  },
  {
    id: "saf-018",
    domain: "patient_safety",
    stem: "Which medication is commonly considered high-alert in community and hospital lists?",
    choices: ["warfarin", "multivitamin gummies", "normal saline nasal spray", "petroleum jelly"],
    correctIndex: 0,
    rationale: "Anticoagulants like warfarin are high-alert.",
    topicTags: ["high-alert", "anticoagulant"],
  },
  {
    id: "saf-019",
    domain: "patient_safety",
    stem: "Sterile compounding areas require attention to:",
    choices: ["Aseptic technique and contamination control per applicable USP standards and policy", "Eating lunch inside the primary engineering control", "Using street clothes without garbing when rushed", "Skipping hand hygiene if gloves are used alone always"],
    correctIndex: 0,
    rationale: "Aseptic technique and garbing protect sterile preparations.",
    topicTags: ["infection-control", "compounding"],
    needsReview: true,
  },
  {
    id: "saf-020",
    domain: "patient_safety",
    stem: "Which is a safe practice for pediatric liquid dosing?",
    choices: ["Using an appropriate metric measuring device and verifying concentration", "Estimating with kitchen spoons", "Rounding all doses to adult tablet strengths blindly", "Ignoring weight-based orders"],
    correctIndex: 0,
    rationale: "Metric devices and concentration checks prevent pediatric dosing errors.",
    topicTags: ["error-prevention", "calculations"],
  },
  {
    id: "saf-021",
    domain: "patient_safety",
    stem: "Adverse drug event reporting systems are valuable because they:",
    choices: ["Help identify patterns and improve safety culture", "Are only for lawsuits", "Replace the need for pharmacist judgment", "Are illegal under HIPAA always"],
    correctIndex: 0,
    rationale: "Reporting supports learning and prevention.",
    topicTags: ["reporting", "quality"],
  },
  {
    id: "saf-022",
    domain: "patient_safety",
    stem: "Which strategy helps prevent insulin mix-ups?",
    choices: ["Differentiating products carefully, verifying concentration (U-100 vs U-500), and using barcodes", "Storing all insulin pens in one unmarked bin", "Assuming all pens are U-100 without checking", "Removing carton labels to save space"],
    correctIndex: 0,
    rationale: "Concentration and product differentiation are critical for insulin safety.",
    topicTags: ["high-alert", "insulin"],
  },
  {
    id: "saf-023",
    domain: "patient_safety",
    stem: "A culture of safety encourages:",
    choices: ["Reporting mistakes and near-misses without fear of unfair punishment for honest system issues", "Hiding errors to protect metrics", "Punishing only the last person who touched the Rx without system review", "Disabling alerts permanently"],
    correctIndex: 0,
    rationale: "Just culture balances accountability with system learning.",
    topicTags: ["quality"],
  },
  {
    id: "saf-024",
    domain: "patient_safety",
    stem: "Which is an example of a sound-alike risk?",
    choices: ["Celebrex and Celexa", "Water and saline irrigation always", "Gloves and syringes", "Paper bags and plastic bags"],
    correctIndex: 0,
    rationale: "Celebrex (celecoxib) and Celexa (citalopram) are a classic sound-alike pair.",
    topicTags: ["LASA"],
  },
  {
    id: "saf-p01",
    domain: "patient_safety",
    stem: "Which pair is a LASA risk?",
    choices: ["hydromorphone and morphine", "toothpaste and floss", "paper and labels", "pens and pencils"],
    correctIndex: 0,
    rationale: "Opioid name/strength confusion is a serious LASA/high-alert issue.",
    topicTags: ["LASA", "opioids"],
    paidOnly: true,
  },
  {
    id: "saf-p02",
    domain: "patient_safety",
    stem: "Why is U-500 insulin especially high-risk?",
    choices: ["It is five times as concentrated as U-100; dosing confusions can cause severe hypoglycemia", "It is Schedule I", "It cannot be refrigerated", "It has no NDC"],
    correctIndex: 0,
    rationale: "U-500 concentration errors are dangerous.",
    topicTags: ["insulin", "high-alert"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "saf-p03",
    domain: "patient_safety",
    stem: "Which best reduces interruption-related errors?",
    choices: ["Creating no-interruption zones for critical verification steps", "Encouraging more simultaneous phone tasks during counting", "Removing all SOPs", "Playing loud music at the bench"],
    correctIndex: 0,
    rationale: "Protected time for critical tasks reduces slips.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p04",
    domain: "patient_safety",
    stem: "Medication error reporting should ideally capture:",
    choices: ["What happened, how it was discovered, and contributing factors", "Only the patient's insurance ID", "Only the technician's personal opinions of coworkers", "Nothing in writing"],
    correctIndex: 0,
    rationale: "Structured reports enable analysis.",
    topicTags: ["reporting", "quality"],
    paidOnly: true,
  },
  {
    id: "saf-p05",
    domain: "patient_safety",
    stem: "Which is a high-alert category often listed by ISMP?",
    choices: ["Opioids", "Most topical steroids of low potency", "Saline nasal sprays", "Sunscreen"],
    correctIndex: 0,
    rationale: "Opioids are high-alert.",
    topicTags: ["high-alert"],
    paidOnly: true,
  },
  {
    id: "saf-p06",
    domain: "patient_safety",
    stem: "Separating adult and pediatric products on shelves helps prevent:",
    choices: ["Wrong strength/formulation selection errors", "HIPAA breaches only", "DSCSA failures only", "DEA Form errors only"],
    correctIndex: 0,
    rationale: "Segregation reduces mix-ups.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p07",
    domain: "patient_safety",
    stem: "Which action is unsafe?",
    choices: ["Overriding allergy alerts without pharmacist review when clinically unclear", "Stopping to clarify an unclear sig", "Scanning barcodes", "Asking for date of birth"],
    correctIndex: 0,
    rationale: "Allergy overrides need clinical judgment by the pharmacist.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p08",
    domain: "patient_safety",
    stem: "Spill management for hazardous drugs should follow:",
    choices: ["Facility hazardous drug policies and appropriate PPE/cleanup kits", "Wiping with bare hands only", "Using food towels from the breakroom only", "Ignoring powders if small"],
    correctIndex: 0,
    rationale: "Hazardous drug spills require trained response.",
    topicTags: ["hazardous-drugs"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "saf-p09",
    domain: "patient_safety",
    stem: "Which improves verbal order safety when verbal orders are allowed?",
    choices: ["Read-back of the order to confirm", "Guessing the drug from partial sounds", "Skipping patient identifiers", "Whispering unclear doses"],
    correctIndex: 0,
    rationale: "Read-back is a standard communication safety practice.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p10",
    domain: "patient_safety",
    stem: "Why avoid trailing zeros on dose notations (e.g., 5.0 mg) in safety conventions?",
    choices: ["They can be misread as a 10x dosing error (50 mg)", "They are required by DEA", "They improve DSCSA tracing", "They are HIPAA mandated"],
    correctIndex: 0,
    rationale: "Trailing zeros are discouraged in many safety notation conventions.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p11",
    domain: "patient_safety",
    stem: "Leading decimal points without a leading zero (e.g., .5 mg) are risky because:",
    choices: ["They may be read as 5 mg", "They always mean 50 mg", "They are preferred notation", "They only apply to OTC"],
    correctIndex: 0,
    rationale: "Use 0.5 mg style to avoid missing the decimal.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p12",
    domain: "patient_safety",
    stem: "Which is a sterile compounding contamination risk?",
    choices: ["Touching critical sites with non-sterile gloves/garb breaches", "Proper hand hygiene and garbing", "Disinfecting vials stoppers appropriately", "Working within the direct compounding area correctly"],
    correctIndex: 0,
    rationale: "Touch contamination of critical sites risks sterility.",
    topicTags: ["compounding", "infection-control"],
    paidOnly: true,
  },
  {
    id: "saf-p13",
    domain: "patient_safety",
    stem: "Patient counseling offers support safety by:",
    choices: ["Catching misunderstandings about directions, allergies, and duplicates", "Replacing all pharmacist checks", "Eliminating the need for labels", "Allowing PHI to be shouted"],
    correctIndex: 0,
    rationale: "Counseling is a final safety net.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p14",
    domain: "patient_safety",
    stem: "Which best describes failure mode and effects analysis (FMEA)?",
    choices: ["A proactive method to find how a process could fail before harm occurs", "Only a post-mortem autopsy of devices", "A DEA inventory form", "A HIPAA authorization"],
    correctIndex: 0,
    rationale: "FMEA is proactive risk assessment.",
    topicTags: ["quality"],
    paidOnly: true,
  },
  {
    id: "saf-p15",
    domain: "patient_safety",
    stem: "Sound-alike pair example:",
    choices: ["Zyrtec and Zyprexa", "Water and ice", "Bags and bottles always", "Pens and markers"],
    correctIndex: 0,
    rationale: "Zyrtec (cetirizine) and Zyprexa (olanzapine) are a known confused pair.",
    topicTags: ["LASA"],
    paidOnly: true,
  },
  {
    id: "saf-p16",
    domain: "patient_safety",
    stem: "High-alert neuromuscular blockers in hospitals require:",
    choices: ["Special storage/labeling safeguards to prevent accidental administration to non-ventilated patients", "OTC shelf placement", "No labeling", "Patient self-selection"],
    correctIndex: 0,
    rationale: "NMBs can cause fatal paralysis if given erroneously.",
    topicTags: ["high-alert"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "saf-p17",
    domain: "patient_safety",
    stem: "Which practice supports cold-chain medication safety?",
    choices: ["Monitoring refrigerator temperatures and segregating stock appropriately", "Storing vaccines next to lunch foods", "Ignoring temperature logs", "Freezing all insulin intentionally"],
    correctIndex: 0,
    rationale: "Temperature control protects product integrity.",
    topicTags: ["quality"],
    paidOnly: true,
  },
  {
    id: "saf-p18",
    domain: "patient_safety",
    stem: "Workaround culture (bypassing safety steps routinely) typically:",
    choices: ["Increases latent system risk", "Improves long-term safety", "Is required by FDA recalls", "Is a HIPAA standard"],
    correctIndex: 0,
    rationale: "Chronic workarounds signal system problems and raise risk.",
    topicTags: ["quality"],
    paidOnly: true,
  },
  {
    id: "saf-p19",
    domain: "patient_safety",
    stem: "Which helps prevent wrong-formulation errors (e.g., ER vs IR)?",
    choices: ["Careful NDC/label checks and system alerts for formulation", "Assuming ER and IR are interchangeable always", "Removing 'ER' from labels for brevity", "Ignoring patient reports of different-looking tablets"],
    correctIndex: 0,
    rationale: "Extended-release vs immediate-release mix-ups are harmful.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p20",
    domain: "patient_safety",
    stem: "A good response after a near-miss includes:",
    choices: ["Documenting and reviewing process gaps", "Mocking the staff member publicly", "Deleting camera footage always", "Increasing speed goals only"],
    correctIndex: 0,
    rationale: "Near-miss learning prevents future harm.",
    topicTags: ["reporting", "quality"],
    paidOnly: true,
  },
  {
    id: "saf-p21",
    domain: "patient_safety",
    stem: "Which is an infection control practice for counting trays?",
    choices: ["Cleaning trays regularly per policy, especially after penicillin/sulfonamide counts when required", "Never cleaning trays", "Using the same tray for hazardous powders without containment", "Licking fingers to separate counting papers"],
    correctIndex: 0,
    rationale: "Tray cleaning reduces cross-contamination/allergen residue risk.",
    topicTags: ["infection-control"],
    paidOnly: true,
  },
  {
    id: "saf-p22",
    domain: "patient_safety",
    stem: "Multi-dose vial safety includes:",
    choices: ["Beyond-use dating after opening per policy and aseptic access", "Sharing needles between patients", "Leaving vials undated indefinitely", "Storing opened vials at room temp always regardless of label"],
    correctIndex: 0,
    rationale: "Opened MDVs need dating and aseptic handling.",
    topicTags: ["infection-control"],
    paidOnly: true,
    needsReview: true,
  },
  {
    id: "saf-p23",
    domain: "patient_safety",
    stem: "Which reduces distraction during final verification?",
    choices: ["Holding non-urgent questions until the check is complete", "Asking multiple questions mid-count simultaneously", "Phone scrolling at the bench", "Overlapping two verifications on one screen hastily"],
    correctIndex: 0,
    rationale: "Protecting attention during verification reduces slips.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  },
  {
    id: "saf-p24",
    domain: "patient_safety",
    stem: "ISMP is best known in pharmacy safety as:",
    choices: ["An organization that publishes medication safety alerts and best practices", "The federal CSA enforcement agency", "A PBM adjudication switch", "A state board of pharmacy"],
    correctIndex: 0,
    rationale: "ISMP provides safety guidance widely used in pharmacies.",
    topicTags: ["quality"],
    paidOnly: true,
  },
  {
    id: "saf-p25",
    domain: "patient_safety",
    stem: "Which pair can be confused due to abbreviations?",
    choices: ["q.d. and q.i.d. if poorly written", "NDC and NPI always meaning the same", "DEA and DOB", "AWP and AAC always identical"],
    correctIndex: 0,
    rationale: "Dangerous abbreviation confusions are a known error source.",
    topicTags: ["error-prevention"],
    paidOnly: true,
  }
];
